#
# Add definitions for CONVERSATION_PROPERTIES and defaults here
#

CONVERSATION_PROPERTIES:
  duration_in_days: 14
  privacy:
    list: "true"
    summary: "true"
    comments: "true"
    invite: "true"
    screen: "true"
    unknown_users: "true"
