#Set a default branch
# set migration command, but only run them when –migrate is specified

environments:
  idea:
    branch: summary_display
    migrate: false
    migration_command: bundle exec rake db:migrate
    maintenance_on_migrate: true
    precompile_assets: true
