#Set a default branch
# set migration command, but only run them when –migrate is specified

environments:
  ce2_solo:
    branch: master
    migrate: false
    migration_command: bundle exec rake db:migrate
    maintenance_on_migrate: true
    precompile_assets: true
    precomplie_assets_task: assets:precompile
    asset_roles: :all

  ce2_solo_clone:
    branch: master
    migrate: false
    migration_command: bundle exec rake db:migrate
    maintenance_on_migrate: true
    precompile_assets: true
    precomplie_assets_task: assets:precompile
    asset_roles: :all

  AUS:
    branch: master
    migrate: false
    migration_command: bundle exec rake db:migrate
    maintenance_on_migrate: true
    precompile_assets: true
    precomplie_assets_task: assets:precompile
    asset_roles: :all

  singapore_live:
    branch: master
    migrate: false
    migration_command: bundle exec rake db:migrate
    maintenance_on_migrate: true
    precompile_assets: true
    precomplie_assets_task: assets:precompile
    asset_roles: :all

  ce2_p4_ng1_4:
    branch: master
    migrate: false
    migration_command: bundle exec rake db:migrate
    maintenance_on_migrate: true
    precompile_assets: true
    precomplie_assets_task: assets:precompile
    asset_roles: :all

